platform :ios, '11.0'
use_frameworks!

target 'AviationKit_Example' do
  pod 'AviationKit', :path => '../'
  pod 'IQKeyboardManagerSwift'

end

target 'AviationKit_Tests' do
  inherit! :search_paths

end
